Minor updates and fixes

diff --git a/demo-error b/demo-error
--- a/demo-error
+++ b/demo-error
@@ -6,7 +6,7 @@
 ###
 ###        USAGE:  demo-error
 ###
-###  DESCRIPTION:  Test various features of shellmenu for debugging
+###  Description:  Demo various features of shmenu for debugging
 ###
 ###      OPTIONS:  --help, --verbose, --quiet
 ### REQUIREMENTS:  ui-functions, shmenu.conf
@@ -96,14 +96,14 @@ while [ ! $INT = 1 ]; do
       : # Do nothing
       ;;
     *)
-      echo "No Selection"
+      vMSG "No Selection"
       exit 0
       ;;
   esac
 
   ### Usage: Dlg ERROR "Some text goes here."
   ###
-  ### This is basically a standard "message box". Always returns exit code 0
+  ### This is a standard "message box". Always returns exit code 0
   ### unless the message box widget failed to run for some reason.
   ###
   ### NOTE: There is a bug in zenity that ignores the height parameter and makes
@@ -111,7 +111,6 @@ while [ ! $INT = 1 ]; do
   ### screen.
 
   Dlg ERROR "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce venenatis odio ut dui aliquam ut condimentum arcu bibendum. Suspendisse iaculis, dolor vitae rutrum elementum, massa sapien egestas quam, at malesuada risus nisi id orci. Nam porttitor faucibus arcu eget pretium. Cras laoreet vestibulum urna, eget hendrerit felis rhoncus non. Praesent laoreet dui enim, vitae cursus ipsum. Quisque ac nisl quam, eu pellentesque lacus. Morbi ac massa dui. Vivamus at quam sed enim ornare gravida. Aenean in neque diam, vel malesuada nunc. Nulla facilisi. Fusce nec sem sit amet ipsum egestas tempor vel vitae sem. Praesent ac facilisis massa. In hac habitasse platea dictumst. Etiam ac orci augue, vel facilisis elit. Morbi a purus vitae nisl egestas dictum."
-  echo $?
-  tPause
+  Dlg INFO "Exit code = $?"
 
 done
diff --git a/demo-info b/demo-info
--- a/demo-info
+++ b/demo-info
@@ -6,7 +6,7 @@
 ###
 ###        USAGE:  demo-info
 ###
-###  DESCRIPTION:  Test various features of shellmenu for debugging
+###  Description:  Demo various features of shmenu for debugging
 ###
 ###      OPTIONS:  --help, --verbose, --quiet
 ### REQUIREMENTS:  ui-functions, shmenu.conf
@@ -96,14 +96,14 @@ while [ ! $INT = 1 ]; do
       : # Do nothing
       ;;
     *)
-      echo "No Selection"
+      vMSG "No Selection"
       exit 0
       ;;
   esac
 
   ### Usage: Dlg INFO "Some text goes here."
   ###
-  ### This is basically a standard "message box". Always returns exit code 0
+  ### This is a standard "message box". Always returns exit code 0
   ### unless the message box widget failed to run for some reason.
   ###
   ### NOTE: There is a bug in zenity that ignores the height parameter and makes
@@ -114,6 +114,6 @@ while [ ! $INT = 1 ]; do
   
 Fusce iaculis elementum massa ac luctus. Donec purus magna, elementum at lacinia ac, varius vel nisl. Nam sed diam neque, nec gravida est. Integer semper magna ac neque egestas pretium. Pellentesque fermentum dui eu felis dapibus volutpat. Praesent aliquet velit a massa pretium sollicitudin. Fusce felis ligula, pretium in congue sed, dictum ut metus. Quisque tellus diam, luctus non varius sed, tristique nec sem. Donec consectetur luctus lorem, et porttitor nunc ultrices tincidunt. Phasellus elementum est at sapien tristique eleifend. Nunc ut nunc fermentum nibh lacinia sollicitudin. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam rhoncus consequat augue, et rutrum massa adipiscing vel. Curabitur quis neque velit, sit amet rutrum mi. Quisque iaculis porttitor est, quis hendrerit nunc pulvinar nec. Donec quis felis leo, id posuere libero."
 
-  echo $?
+  Dlg INFO "Exit code = $?"
 
 done
diff --git a/wrapup b/wrapup
--- a/wrapup
+++ b/wrapup
@@ -1,9 +1,113 @@
 #!/bin/bash
 
-# Wrap-up for shellmenu
+###============================================================================
+###
+###         FILE:  wrapup
+###
+###        USAGE:  wrapup
+###
+###  Description:  Quickly archive everything
+###
+###      OPTIONS:  --help, --verbose, --quiet, -cui, -tui, -gui
+### REQUIREMENTS:  ui-functions, shmenu.conf
+###         BUGS:  ---
+###        NOTES:  ---
+###       AUTHOR:  Michael A. Taylor (mataylortech@gmail.com)
+###      COMPANY:  ---
+###      VERSION:  Beta
+###      CREATED:  04/03/2013
+###     REVISION:  04/03/2013
+###============================================================================
 
-#f=($(ls | egrep -v "~" ))
+# Source
+. ./ui-functions
+. ./shmenu.conf
 
-f=$(ls)
+scriptname=$(basename $0)
+TMP=`mktemp /tmp/${scriptname}.XXXXXX`
 
-tar -cf ~/Dropbox/Private/devscripts/shmenu/shmenu_`date +%y%m%d`.tar ${f[*]}
+# Set a trap to remove the temp file when the program exits.
+trap cleanup HUP QUIT TERM EXIT
+trap interrupt INT
+
+#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
+# FUNCTIONS
+#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+interrupt() {
+  ## Trap Cntrl-C, set INT to 1
+  INT=1
+} # End of interrupt
+
+cleanup() {
+  ## Remove temp file if it exists.
+  [ -f "$TMP" ] && rm -f $TMP
+} # End of cleanup
+
+usage_help() {
+  ## Display title header to standard output
+  cat "$0" | egrep '^###'
+  return 0
+} # End of Usage
+
+#------------------------------------------------------------------------------
+# PRE-PROCESSING
+#------------------------------------------------------------------------------
+
+# Initialize variables and arrays
+INT=0
+
+# Parse command-line parameters
+
+while [ $# -gt 0 ]; do
+  case "$1" in
+    -h|--help)
+      usage_help
+      exit 0
+      ;; 
+    -v|--verbose)
+      verbose=0
+      shift
+      ;;
+    -q|--quiet)
+      verbose=1
+      shift
+      ;;
+    -g|--gui)
+      GUI=1
+      shift
+      ;;
+    -t|--tui)
+      GUI=0
+      shift
+      ;;
+    -c|--cli|--cui)
+      GUI=-1
+      shift
+      ;;
+    *)
+      ErrorMsg "Invalid parameter" $0
+      exit 1
+      ;;
+  esac
+done
+
+#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
+# MAIN
+#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
+
+# Set GUI style
+sed "s/GUI_DEFAULT=.*/GUI_DEFAULT=$GUI/" "./shmenu.conf" >$TMP
+# Backup old config file
+cp -f "./shmenu.conf" "./shmenu.conf~"
+cp -f $TMP "./shmenu.conf"
+. ./shmenu.conf
+
+# Wrap-up all files into an archive.
+
+folder=$(basename $PWD)
+pushd ..
+tar -cvzf ~/Dropbox/Private/devscripts/shmenu/shmenu_`date +%y%m%d`.tar.gz $folder --exclude=".git*"
+popd
+#${f[*]}
+
